services:
  - type: web
    name: my-django-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn churchsite.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
