# Generated by Django 5.2.2 on 2025-06-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sitecontent_delete_welcomemessage_book_added_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
