# Generated by Django 5.2.2 on 2025-06-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_shopitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
